<div class="col-xl-8 offset-xl-2"><div class="card" id="receipt">
    <div class="card-header"><div><h3>{{ $sale->sale_number }}</h3><span class="badge {{ $sale->status === 'completed' ? 'badge-success' : 'badge-danger' }}">{{ strtoupper($sale->status) }}</span></div><div class="no-print"><a href="{{ route('pos-sales.index') }}" class="btn btn-light">Back</a><button onclick="window.print()" class="btn btn-primary">Print</button></div></div>
    <div class="card-body">
        <div class="row mb-4"><div class="col-6"><small>Date</small><div>{{ $sale->created_at->format('d M Y H:i') }}</div><small class="mt-2 d-block">Cashier</small><div>{{ optional($sale->cashier)->full_name }}</div></div><div class="col-6 text-end"><small>Customer</small><div>{{ $sale->customer_name ?: '-' }}</div><small class="mt-2 d-block">Payment</small><div>{{ optional(optional($sale->payments->first())->methodPayment)->name }}</div></div></div>
        <table class="table"><thead><tr><th>Item</th><th>Qty</th><th>Price</th><th class="text-end">Subtotal</th></tr></thead><tbody>@foreach ($sale->items as $item)<tr><td>{{ $item->product_name }}</td><td>{{ $item->quantity }}</td><td>Rp. {{ number_format($item->unit_price, 0, ',', '.') }}</td><td class="text-end">Rp. {{ number_format($item->subtotal, 0, ',', '.') }}</td></tr>@endforeach</tbody></table>
        <div class="row"><div class="col-md-6"></div><div class="col-md-6"><div class="d-flex justify-content-between"><span>Subtotal</span><span>Rp. {{ number_format($sale->subtotal, 0, ',', '.') }}</span></div><div class="d-flex justify-content-between"><span>Discount</span><span>Rp. {{ number_format($sale->discount_amount, 0, ',', '.') }}</span></div><div class="d-flex justify-content-between fs-4"><strong>Total</strong><strong>Rp. {{ number_format($sale->grand_total, 0, ',', '.') }}</strong></div><div class="d-flex justify-content-between"><span>Paid</span><span>Rp. {{ number_format($sale->paid_amount, 0, ',', '.') }}</span></div><div class="d-flex justify-content-between"><span>Change</span><span>Rp. {{ number_format($sale->change_amount, 0, ',', '.') }}</span></div></div></div>
        @if ($sale->status === 'void')<div class="alert alert-danger mt-4"><strong>Void:</strong> {{ $sale->void_reason }} ({{ optional($sale->voided_at)->format('d M Y H:i') }})</div>@endif
    </div>
    @if ($sale->status === 'completed' && Auth::user()->isAdmin())
        <div class="card-footer no-print"><form action="{{ route('pos-sales.void', $sale->id) }}" method="POST" onsubmit="return confirm('Void transaksi dan kembalikan seluruh stok?')">@csrf<div class="input-group"><input class="form-control" name="void_reason" placeholder="Alasan void wajib diisi" required><button class="btn btn-danger">Void Transaction</button></div></form></div>
    @endif
</div></div>
<style media="print">.dlabnav,.nav-header,.header,.no-print{display:none!important}.content-body{margin:0!important}.container-fluid{padding:0!important}#receipt{box-shadow:none!important}</style>
